title: Diplomado en Economía Social y Desarrollo Local
description: MÓDULO 5. Herramientas Informáticas Útiles para la Gestión Democrática en las Entidades de la Economía Social
theme: jekyll-theme-midnight
lang: es

